version: '3.8'

services:
  backend:
    build: ./backend
    container_name: zoo_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    networks:
      - zoo_network

  frontend:
    build: ./frontend
    container_name: zoo_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - zoo_network

  nginx:
    image: nginx:latest
    container_name: zoo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - zoo_network

networks:
  zoo_network:
