version: '3.8'
services:
  api:
    build:
      context: /home/admin/ZooArcadia
      dockerfile: docker/Dockerfile.back
    container_name: zooarcadia_api
    restart: unless-stopped
    networks:
      - zooarcadia_net
    expose:
      - "9000"
    ports:
      - "9000:9000"

  front:
    build:
      context: /home/admin/ZooArcadia
      dockerfile: docker/Dockerfile.front
    container_name: zooarcadia_front
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - zooarcadia_net

networks:
  zooarcadia_net:
    driver: bridge
