FROM node:18-alpine AS builder

WORKDIR /app
COPY ../../frontend_arcadia/package*.json ./
RUN npm install
COPY ../../frontend_arcadia/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]