version: '3.8'
services:
  api:
    build:
      context: /home/admin/ZooArcadia
      dockerfile: docker/Dockerfile.back
    container_name: zooarcadia_api
    restart: unless-stopped
    environment:
      # Bases de données hébergées sur l'hôte
      DATABASE_URL: "mysql://user:password@185.158.107.98:3306/zooarcadia_db"
      # Si besoin de MongoDB, décommente et ajuste
      # MONGODB_URL: "mongodb://user:password@185.158.107.98:27017/zooarcadia_mongo"
    volumes:
      - ../backend_arcadia:/var/www/api
    networks:
      - zooarcadia_net
    expose:
      - "9000"
    ports:
      - "9000:9000"
    #entrypoint: >
    #  sh -c "chown -R www-data:www-data /var/www/api"

  front:
    build:
      context: /home/admin/ZooArcadia
      dockerfile: docker/Dockerfile.front
    container_name: zooarcadia_front
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - zooarcadia_net

networks:
  zooarcadia_net:
    driver: bridge
